# -*- coding: utf-8 -*-
"""MENU IMAGE TO AUDIO - GOOGLE COLAB VERSION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mho0-czfE7v2as9Q9tk3J-gPyGXWiwev
"""

!pip install google-generativeai pillow gtts requests -q


import google.generativeai as genai
from PIL import Image
from gtts import gTTS
from IPython.display import Audio, display
import requests
from io import BytesIO
import os

def setup_gemini():
    GEMINI_API_KEY = "AIzaSyAjASmxejbhAiMb45lQtradV1vFktnx0tE"
    if GEMINI_API_KEY == "YOUR_FREE_API_KEY_HERE":
        print(" Replace with your actual Gemini API key!")
        return None
    genai.configure(api_key=GEMINI_API_KEY)
    return genai

def extract_text_from_image(image_path_or_url):
    gemini = setup_gemini()
    if not gemini:
        return None
    model = gemini.GenerativeModel('gemini-2.5-flash')

    if image_path_or_url.startswith('http'):
        response = requests.get(image_path_or_url, timeout=10)
        img = Image.open(BytesIO(response.content))
    else:
        img = Image.open(image_path_or_url)

    prompt = [
        "Extract ALL text from this menu image accurately. Return only raw text with lines preserved.",
        img
    ]
    response = model.generate_content(prompt)
    return response.text

def text_to_speech(text, language='en', filename='menu_audio.mp3'):
    clean_text = text.replace('*','').replace('#','').replace('\n',' ')
    tts = gTTS(text=clean_text, lang=language, slow=False)
    tts.save(filename)
    return filename


def menu_image_to_audio():
    print(" MENU IMAGE TO AUDIO")

    print(" Choose input method:")
    print("1. Sample menu image URL")
    print("2. Upload your own image")
    print("3. Enter image URL")

    choice = input("Enter choice (1/2/3): ").strip()

    if choice == "1":
        image_path = "https://i.imgur.com/G4h3QyG.png"
    elif choice == "2":
        from google.colab import files
        uploaded = files.upload()
        if uploaded:
            image_path = list(uploaded.keys())[0]
        else:
            print(" No file uploaded!"); return
    elif choice == "3":
        image_path = input("Enter image URL: ").strip()
        if not image_path:
            print(" No URL provided!"); return
    else:
        print(" Invalid choice!"); return

    print(" Extracting text from image...")
    extracted_text = extract_text_from_image(image_path)
    if not extracted_text:
        print(" Failed to extract text!"); return

    print("\n Extracted Text:")
    print("-"*50)
    print(extracted_text)
    print("-"*50)

    print("\n Converting extracted text to audio...")
    if os.path.exists("menu_audio.mp3"): os.remove("menu_audio.mp3")
    audio_file = text_to_speech(extracted_text, language='en')

    print(" Audio generated successfully! ")
    display(Audio(audio_file, autoplay=True))


menu_image_to_audio()